version: '3.9'

services:
  guacd:
    container_name: guacd
    image: donswanson/guacd
    networks:
      - guacnetwork
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./recordings:/recordings:rw

  postgres:
    container_name: postgres_guac
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: guac_db
      POSTGRES_PASSWORD: '<POSTGRES_PASSWORD>'
      POSTGRES_USER: guac_user
    image: postgres:latest
    networks:
      - guacnetwork
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guac_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: '<POSTGRES_PASSWORD>'
      POSTGRES_USERNAME: guac_user
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
      #TOTP_ENABLED: true
      TZ: America/Chicago
    image: donswanson/guacamole
    networks:
      - guacnetwork
    volumes:
      - ./recordings:/recordings:rw
    ports:
      - 8080:8080
    restart: always

networks:
  guacnetwork:
    driver: bridge
