version: '3.9'

services:
  guacd:
    container_name: guacd
    image: donswanson/guacd
    networks:
      - guacnetwork
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    container_name: postgres_guac
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guac_db
      POSTGRES_PASSWORD: '<POSTGRES_PASSWORD>'
      POSTGRES_USER: guac_user
    image: postgres:15.8-alpine
    networks:
      - guacnetwork
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guac_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: '<POSTGRES_PASSWORD>'
      POSTGRES_USER: guac_user
      TZ: America/Chicago
    image: donswanson/guacamole
    networks:
      - guacnetwork
    volumes:
      - ./record:/record:rw
      - /docker/guac_build/extensions:/opt/guacamole/extensions:rw
      - /docker/guac_build/lib:/opt/guacamole/lib:rw
    ports:
      - 8080:8080
    restart: always

networks:
  guacnetwork:
    driver: bridge
