version: 2.1
executors:
  x86_64:
    docker:
      - image: cimg/base:current
  arm64:
    docker:
      - image: cimg/base:current
    resource_class: arm.large
commands:
  build-server:
    description: "Build Server"
    parameters:
      arch:
        type: string
    steps:
      - run: 
          #Temp Fix until 1.6.0 is released
          #echo 'export BRANCH=$(curl "https://api.github.com/repos/apache/guacamole-server/tags" | jq -r ".[0].name")' >> "$BASH_ENV"
          echo 'export BRANCH=1.6.0' >> "$BASH_ENV"
      - run: 
          #Temp Fix until 1.6.0 is released
          git clone --branch=staging/1.6.0 "https://github.com/apache/guacamole-server" .
          #git clone "https://github.com/apache/guacamole-server" .

      - run:
          name: Temporary Patch to fix FREE RDP OPS on arm64
          environment:
            ARCH: <<parameters.arch>>
          command: | 
            if [ $ARCH = "arm64" ]; then
              sed -i "s/-DWITH_SSE2=ON/-DWITH_SSE2=OFF/" Dockerfile
            else
              echo "pass"
            fi
      - run:
          name: Build Docker image
          command: |
            TAG=${BRANCH}-<<parameters.arch>>
            docker build -t $DOCKERHUB_USERNAME/guacd:$TAG .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load and Publish Docker image
          command: |
            TAG=${BRANCH}-<<parameters.arch>>
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/guacd:$TAG
  
  build-client:
    description: "Build Client"
    parameters:
      arch:
        type: string
    steps:
      - run: 
          #Temp Fix until 1.6.0 is released
          #echo 'export BRANCH=$(curl "https://api.github.com/repos/apache/guacamole-client/tags" | jq -r ".[0].name")' >> "$BASH_ENV"
          echo 'export BRANCH=1.6.0' >> "$BASH_ENV"
      - run: 
          #Temp Fix until 1.6.0 is released
          git clone --branch=staging/1.6.0 "https://github.com/apache/guacamole-client" .
          #git clone "https://github.com/apache/guacamole-client" .
      - run:
          name: Build Docker image
          command: |
            TAG=${BRANCH}-<<parameters.arch>>
            docker build -t $DOCKERHUB_USERNAME/guacamole:$TAG .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load and Publish Docker image
          command: |
            TAG=${BRANCH}-<<parameters.arch>>
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/guacamole:$TAG

jobs:
  build_arm64_client:
    executor: arm64
    steps:
      - build-client:
          arch: arm64

  build_x86_64_client:
    executor: x86_64
    steps:
      - build-client:
          arch: x86_64

  build_arm64_server:
    executor: arm64
    steps:
      - build-server:
          arch: arm64

  build_x86_64_server:
    executor: x86_64
    steps:
      - build-server:
          arch: x86_64
  
  publish_manifest:
    docker:
      - image: cimg/base:current
    steps:
      - run: 
          #Temp Fix until 1.6.0 is released
          #echo 'export BRANCH=$(curl "https://api.github.com/repos/apache/guacamole-client/tags" | jq -r ".[0].name")' >> "$BASH_ENV"
          echo 'export BRANCH=1.6.0' >> "$BASH_ENV"
      - run:
          name: Publish manifests
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker manifest create $DOCKERHUB_USERNAME/guacd:${BRANCH} $DOCKERHUB_USERNAME/guacd:${BRANCH}-x86_64 $DOCKERHUB_USERNAME/guacd:${BRANCH}-arm64
            docker manifest push $DOCKERHUB_USERNAME/guacd:${BRANCH}
            docker manifest create $DOCKERHUB_USERNAME/guacd:latest $DOCKERHUB_USERNAME/guacd:${BRANCH}-x86_64 $DOCKERHUB_USERNAME/guacd:${BRANCH}-arm64
            docker manifest push $DOCKERHUB_USERNAME/guacd:latest
            docker manifest create $DOCKERHUB_USERNAME/guacamole:${BRANCH} $DOCKERHUB_USERNAME/guacamole:${BRANCH}-x86_64 $DOCKERHUB_USERNAME/guacamole:${BRANCH}-arm64
            docker manifest push $DOCKERHUB_USERNAME/guacamole:${BRANCH}
            docker manifest create $DOCKERHUB_USERNAME/guacamole:latest $DOCKERHUB_USERNAME/guacamole:${BRANCH}-x86_64 $DOCKERHUB_USERNAME/guacamole:${BRANCH}-arm64
            docker manifest push $DOCKERHUB_USERNAME/guacamole:latest

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_arm64_client
      - build_arm64_server
      - build_x86_64_client
      - build_x86_64_server
      - publish_manifest:
          requires:
            - build_arm64_client
            - build_arm64_server
            - build_x86_64_client
            - build_x86_64_server
